### ISSUE TITLE
id1 vs unit

### ISSUE THREAD

**Issue by andreasabel** [nachivpn/cc#1]
https://github.com/nachivpn/cc/blob/386d548ab4c93b7b1d35ac4559880a4b1058f5d7/src/CCLBeta/CCL.agda#L133

Isn't `id1` a special case of `unit` and thus redundant?

**Comment by nachivpn** [comment]
It could very well be replaced with `unit`, but if we do this, "tracing" the reduction steps of normalization (i.e., showing `t ⟶* embNf (norm t)` will need the reduction rule `f : Tm a 𝟙 ⟶ unit`, which unlike the other rules (in [CCL.agda](https://github.com/nachivpn/cc/blob/master/src/CCLBeta/CCL.agda)) is type-driven. The current rules are all structural, and hence still applicable in the untyped setting (which is the case for CCLβ in Curien's categorical combinators).  

I didn't add any eta (type-driven) rules to this calculus simply because I wanted to focus on the complexity of implementing a model that admits weakening. Adding the remaining CCC rules would be next step (if this works out, that is!).

(Although we already spoke about this. I thought it might be worthwhile to document it here.)
